# Generated by Django 5.2.3 on 2025-06-25 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Aseguradora')),
                ('telefono_contacto', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Aseguradora',
                'verbose_name_plural': 'Aseguradoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Marca del Vehiculo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Modelo')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='gestion_flota.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['marca', 'nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='gestion_flota.provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['provincia', 'nombre'],
                'unique_together': {('provincia', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('acreedor_hipotecario', models.BooleanField(default=False, verbose_name='Tiene acreedor hipotecario')),
                ('is_carga', models.BooleanField(default=False, verbose_name='Es vehículo de carga')),
                ('ano_fabricacion', models.PositiveBigIntegerField(verbose_name='Ano de Fabricacion')),
                ('numero_motor', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numero de Motor')),
                ('color', models.CharField(blank=True, max_length=30)),
                ('tipo_combustible', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel'), ('ELECTRICO', 'Electrico'), ('HIBRIDO', 'Hibrido')], default='GASOLINA', max_length=20)),
                ('mes_renovacion_placa', models.CharField(choices=[('ENERO', 'Enero'), ('FEBRERO', 'Febrero'), ('MARZO', 'Marzo'), ('ABRIL', 'Abril'), ('MAYO', 'Mayo'), ('JUNIO', 'Junio'), ('JULIO', 'Julio'), ('AGOSTO', 'Agosto'), ('SEPTIEMBRE', 'Septiembre'), ('OCTUBRE', 'Octubre'), ('NOVIEMBRE', 'Noviembre'), ('DICIEMBRE', 'Diciembre')], default='ENERO', max_length=100)),
                ('estado_placa', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido')], default='VIGENTE', max_length=20, verbose_name='Estado de la Placa')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='gestion_flota.modelo')),
                ('municipio_placa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_registrados', to='gestion_flota.municipio', verbose_name='Municipio de la placa')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['-ano_fabricacion', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaPesosDimensiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_permiso', models.CharField(max_length=50, unique=True, verbose_name='Número de Permiso')),
                ('entidad_emisora', models.CharField(max_length=200, verbose_name='Entidad Emisora')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('peso_maximo_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Máximo Autorizado (kg)')),
                ('dimensiones', models.CharField(blank=True, max_length=100, verbose_name='Dimensiones (Largo x Ancho x Alto)')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas_pesos_dimensiones', to='gestion_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Tarjeta de Pesos y Dimensiones',
                'verbose_name_plural': 'Tarjetas de Pesos y Dimensiones',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_poliza', models.CharField(max_length=50, unique=True, verbose_name='Número de Póliza')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('activa', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='gestion_flota.aseguradora')),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poliza', to='gestion_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Póliza de Seguro',
                'verbose_name_plural': 'Pólizas de Seguro',
                'ordering': ['-fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Corregimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Corregimiento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corregimientos', to='gestion_flota.municipio')),
            ],
            options={
                'verbose_name': 'Corregimiento',
                'verbose_name_plural': 'Corregimientos',
                'unique_together': {('municipio', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RevisadoVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taller_certificado', models.CharField(max_length=200, verbose_name='Taller Certificado')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número de Documento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('aprobado', models.BooleanField(default=True, verbose_name='Aprobado')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('POR_VENCER', 'Por Vencer'), ('VENCIDO', 'Vencido')], default='VIGENTE', max_length=20, verbose_name='Estado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisados', to='gestion_flota.vehiculo')),
            ],
            options={
                'verbose_name': 'Revisado Vehicular',
                'verbose_name_plural': 'Revisados Vehiculares',
                'ordering': ['-fecha_vencimiento'],
                'unique_together': {('vehiculo', 'fecha_emision')},
            },
        ),
    ]
