# Generated by Django 5.2.3 on 2025-06-25 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('gestion_flota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='corregimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='gestion_flota.corregimiento', verbose_name='Corregimiento'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_por_distrito', to='gestion_flota.municipio', verbose_name='Distrito'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='gestion_flota.provincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='accounts.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
